### ISSUE TITLE
Credentials?

### ISSUE THREAD

**Issue by rubendob** [basak/glacier-cli#35]
HI

I don't understand how pass aws credentials to glacier-cli

 glacier vault list
Traceback (most recent call last):
  File "/usr/local/bin/glacier", line 730, in <module>
    App().main()
  File "/usr/local/bin/glacier", line 705, in **init**
    connection = boto.glacier.connect_to_region(args.region)
  File "/root/scripts/glacier-cli/boto/glacier/**init**.py", line 56, in connect_to_region
    return region.connect(*_kw_params)
  File "/root/scripts/glacier-cli/boto/regioninfo.py", line 62, in connect
    return self.connection_cls(region=self, *_kw_params)
  File "/root/scripts/glacier-cli/boto/glacier/layer2.py", line 38, in **init**
    self.layer1 = Layer1(_args, *_kwargs)
  File "/root/scripts/glacier-cli/boto/glacier/layer1.py", line 63, in **init**
    suppress_consec_slashes)
  File "/root/scripts/glacier-cli/boto/connection.py", line 525, in **init**
    host, config, self.provider, self._required_auth_capability())
  File "/root/scripts/glacier-cli/boto/auth.py", line 621, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials

Does anybody any clue?

thanks

**Comment by okainov** [comment]
Why is this closed?
