### ISSUE TITLE
SSL certificate verify failed on upload

### ISSUE THREAD

**Issue by amedee** [basak/glacier-cli#63]
I uploaded a 6.6 GiB file and after some time I got this error:

```
Traceback (most recent call last):
  File "/home/amedee/bin/glacier", line 730, in <module>
    App().main()
  File "/home/amedee/bin/glacier", line 716, in main
    self.args.func()
  File "/home/amedee/bin/glacier", line 498, in archive_upload
    file_obj=self.args.file, description=name)
  File "/home/amedee/bin/glacier-cli/boto/glacier/vault.py", line 141, in create_archive_from_file
    writer.write(data)
  File "/home/amedee/bin/glacier-cli/boto/glacier/writer.py", line 152, in write
    self.send_part()
  File "/home/amedee/bin/glacier-cli/boto/glacier/writer.py", line 141, in send_part
    content_range, part)
  File "/home/amedee/bin/glacier-cli/boto/glacier/layer1.py", line 626, in upload_part
    response_headers=response_headers)
  File "/home/amedee/bin/glacier-cli/boto/glacier/layer1.py", line 83, in make_request
    data=data)
  File "/home/amedee/bin/glacier-cli/boto/connection.py", line 913, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/home/amedee/bin/glacier-cli/boto/connection.py", line 859, in _mexe
    raise e
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

I don't know if the file was uploaded correctly, but the time was long enough to expect an upload to complete. The `glacier archive list` command doesn't show the file.

I have previously used `glacier archive retrieve` and `glacier vault sync` on this system, and they do not return an error.

**Comment by amedee** [comment]
The 6.6 GiB was a tarball that contained some redundant files. I removed the redundant files, the resulting file was 2.6 GiB. I was able to upload the smaller file.
So probably the error only occurs with very large files, but I wouldn't be able to determine the cut-off size, and the issue is no longer relevant for me personally. But maybe others will have the same issue.

**Comment by briceb8e** [comment]
I believe the max size per archive is 4GB:
https://docs.aws.amazon.com/amazonglacier/latest/dev/uploading-archive-mpu.html
