### ISSUE TITLE
with git-annex context - reading from stdin with python3 requires .buffer

### ISSUE THREAD

**Issue by cnjr2** [basak/glacier-cli#74]
Thank you for the project.

I have been using it in the context of `git-annex`. My system has `python3` installed and that seems to cause problems when reading from `sys.stdin` as provided by `git-annex`:

```
git annex move text_file.txt --to glacier
move text_file.txt (checking glacier...) (to glacier...)
100%  13 B               27 B/s 0sTraceback (most recent call last):
  File "/Users/username/.local/bin/glacier", line 740, in <module>
    main()
  File "/Users/username/.local/bin/glacier", line 736, in main
    App().main()
  File "/Users/username/.local/bin/glacier", line 722, in main
    self.args.func()
  File "/Users/username/.local/bin/glacier", line 504, in archive_upload
    file_obj=self.args.file, description=name)
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/vault.py", line 178, in create_archive_from_file
    writer.close()
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/writer.py", line 228, in close
    self.partitioner.flush()
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/writer.py", line 79, in flush
    self._send_part()
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/writer.py", line 64, in _send_part
    data = b''.join(self._buffer)
TypeError: sequence item 0: expected a bytes-like object, str found

100%  13 B               17 B/s 0sTraceback (most recent call last):
  File "/Users/username/.local/bin/glacier", line 740, in <module>
    main()
  File "/Users/username/.local/bin/glacier", line 736, in main
    App().main()
  File "/Users/username/.local/bin/glacier", line 722, in main
    self.args.func()
  File "/Users/username/.local/bin/glacier", line 504, in archive_upload
    file_obj=self.args.file, description=name)
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/vault.py", line 178, in create_archive_from_file
    writer.close()
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/writer.py", line 228, in close
    self.partitioner.flush()
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/writer.py", line 79, in flush
    self._send_part()
  File "/Users/username/.pyenv/versions/3.7.3/lib/python3.7/site-packages/boto/glacier/writer.py", line 64, in _send_part
    data = b''.join(self._buffer)
TypeError: sequence item 0: expected a bytes-like object, str found
failed
git-annex: move: 1 failed
```

When reading from `sys.stdin.read()`, one needs to use `sys.stdin.buffer.read()` instead. I got it to work with that change. 

```
git annex move text_file.txt --to glacier
move text_file.txt (checking glacier...) (to glacier...)
ok
(recording state in git...)
```

I will create a pull request with a patch.

**Comment by basak** [comment]
Thank you for the report! I'm happy that you find this project useful.

I commented in the pull request. Hopefully we'll be able to figure this out and get this fixed soon.

I just wanted to point out here that this was written against Python 2 before boto (the underlying AWS library) supported Python 3 - so against a previous version of PEP 394, effectively.

It might be more correct to change shebang to `/usr/bin/python2` to properly declare this a Python 2 -only project until it's properly ported to Python 3.

However since we should move properly to Python 3 anyway, I'm grateful for any fixes to make this project work on both versions, and I see no need to adjust the shebang.

**Comment by cnjr2** [comment]
I think in the context of git-annex, the file is opened as a textfile. When debugging yesterday, I have noticed that `file.mode=r`. So it is my suspicion that somewhere from `argparse` to `archive_upload(file_obj=self.args.file, description=name)`, the instruction to open a binary file is lost?

Here are some links of evidence (admittedly circumstantial and old) for python2 vs python3 use of `.read`:
- https://groups.google.com/forum/#!topic/comp.lang.python/CsT0chIPtRw
- https://programtalk.com/python-examples/sys.stdin.buffer.read/

**Comment by soxofaan** [comment]
I think I'm stumbling on the same issue (using python 3.7), but my stack trace is:
```
  File "/Users/u/src/glacier-cli/glacier.py", line 722, in main
    self.args.func()
  File "/Users/u/src/glacier-cli/glacier.py", line 500, in archive_upload
    file_obj=self.args.file, description=name)
  File "/Users/u/src/glacier-cli/venv37/lib/python3.7/site-packages/boto/glacier/vault.py", line 174, in create_archive_from_file
    data = file_obj.read(part_size)
  File "/Users/u/usr/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 0: invalid start byte
```

(using boto 2.48.0 in my env FYI)

I was also trying to debug this and noticed like @cnjr2 that the file (stdin actually) in `archive_upload` was not in `rb` mode:
```
file=<_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>
```

It seems that the "rb" mode as requested in https://github.com/basak/glacier-cli/blob/89828628694367b54f6c9b418c4de0ba6b3f5362/glacier.py#L670-L671
is lost in argparse:
```python
class FileType(object):
    ...
    def __init__(self, mode='r', bufsize=-1, encoding=None, errors=None):
        self._mode = mode
        ...
    def __call__(self, string):
        # the special argument "-" means sys.std{in,out}
        if string == '-':
            if 'r' in self._mode:
                return _sys.stdin
            elif ...

        # all other arguments are used as file names
        try:
            return open(string, self._mode, self._bufsize, self._encoding,
                        self._errors)
```

When file argument is `-`, `sys.stdin` is used directly, regardless of the requested mode ("rb" in this case)

**Comment by basak** [comment]
This is resolved now I think?
