### ISSUE TITLE
Exception ends upload of very large file

### ISSUE THREAD

**Issue by khagler** [basak/glacier-cli#8]
Attempts to upload a very large (288.64 GB) file run for about an hour or two, then fail with the following output:

> frontier:glacier-cli khagler$ ./glacier.py archive upload Photos ~/Documents/photos.tgz 
> Traceback (most recent call last):
>   File "./glacier.py", line 618, in <module>
>     App().main()
>   File "./glacier.py", line 604, in main
>     args.func(args)
>   File "./glacier.py", line 416, in archive_upload
>     archive_id = vault.create_archive_from_file(file_obj=args.file, description=name)
>   File "/Users/khagler/glacier/glacier-cli/boto/glacier/vault.py", line 141, in create_archive_from_file
>     writer.write(data)
>   File "/Users/khagler/glacier/glacier-cli/boto/glacier/writer.py", line 152, in write
>     self.send_part()
>   File "/Users/khagler/glacier/glacier-cli/boto/glacier/writer.py", line 141, in send_part
>     content_range, part)
>   File "/Users/khagler/glacier/glacier-cli/boto/glacier/layer1.py", line 626, in upload_part
>     response_headers=response_headers)
>   File "/Users/khagler/glacier/glacier-cli/boto/glacier/layer1.py", line 83, in make_request
>     data=data)
>   File "/Users/khagler/glacier/glacier-cli/boto/connection.py", line 913, in make_request
>     return self._mexe(http_request, sender, override_num_retries)
>   File "/Users/khagler/glacier/glacier-cli/boto/connection.py", line 859, in _mexe
>     raise e
> socket.gaierror: [Errno 8] nodename nor servname provided, or not known

OS: Mac OS X 10.7.5 Server
Python 2.7.1

I tried uploading the same file using FastGlacier with the part size set to 1 GB. It would upload some of each part before failing with a message about the remote host dropping the connection. After setting the part size to 256 MB, it was able to upload individual parts successfully.

Addendum:

After a bit more investigation, I _think_ I've figured out what might be going on. According to the Amazon documentation, the maximum number of parts for a multi-part upload is 10,000. For this (very large) archive to be split evenly into 10,000 parts, each part would have to be about 27.5 MB--or, given the limits on allowable part sizes, 32 MB. It looks like you're using a default part size (which I didn't realize at the time I could change) of 8 MB. If I'm right about that, then an 80 GB file would be a (marginally less painful) valid test.

**Comment by strobe33333** [comment]
I too am having this problem
